"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ka"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.getStarted": "Get Started",

    // Hero Section (Main Page)
    "hero.title": "Transforming Ideas Into Digital Reality",
    "hero.subtitle": "We build innovative software solutions that drive business growth and enhance user experience",
    "hero.cta": "Explore Our Services",
    "hero.secondary": "Contact Us",

    // Services Section (Main Page & Services Page)
    "services.title": "Our Services",
    "services.subtitle": "Comprehensive software development solutions tailored to your needs",
    "services.webDev": "Web Development",
    "services.webDesc": "Custom websites and web applications with modern technologies",
    "services.mobileDev": "Mobile Development",
    "services.mobileDesc": "Native and cross-platform mobile applications for iOS and Android",
    "services.cloudSolutions": "Cloud Solutions",
    "services.cloudDesc": "Scalable cloud infrastructure and deployment services",
    "services.consultancy": "IT Consultancy",
    "services.consultancyDesc": "Expert advice on technology strategy and implementation",

    // About Section (Main Page & About Page)
    "about.title": "About Medusa",
    "about.subtitle": "A team of passionate developers creating exceptional software",
    "about.story": "Our Story",
    "about.mission": "Our Mission",
    "about.vision": "Our Vision",
    "about.team": "Our Team",

    // Technologies Section (Main Page)
    "tech.title": "Technologies We Use",
    "tech.subtitle": "We leverage cutting-edge technologies to deliver high-quality solutions",

    // Testimonials Section (REMOVED FROM MAIN PAGE, but keys kept for potential other uses)
    "testimonials.title": "What Our Clients Say",
    "testimonials.subtitle": "Hear from businesses we've helped transform",

    // Contact Section (Main Page & Contact Page)
    "contact.title": "Get In Touch",
    "contact.subtitle": "We'd love to hear from you",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.submit": "Send Message",
    "contact.address": "Address",
    "contact.phone": "Phone",
    // "contact.email": "Email", // Duplicate, already exists

    // Footer
    "footer.rights": "All rights reserved",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.companyInfo": "Transforming ideas into digital reality with innovative software solutions.",

    // Home Page Specific
    "home.cta.title": "Ready to Transform Your Ideas Into Reality?",
    "home.cta.subtitle": "Let's build something amazing together. Contact us today to discuss your project.",
    "home.cta.getStarted": "Get Started",
    "home.cta.learnMore": "Learn More",
    "home.features.title": "Why Choose Medusa for Your Software Development?",
    "home.features.subtitle": "We combine technical expertise with creative problem-solving to deliver exceptional software solutions.",
    "home.features.item1": "Expert team of developers, designers, and strategists",
    "home.features.item2": "Cutting-edge technologies and best practices",
    "home.features.item3": "Agile development methodology for faster delivery",
    "home.features.item4": "Scalable solutions that grow with your business",
    "home.features.item5": "Dedicated support and maintenance services",
    "home.features.exploreServices": "Explore Our Services",

    // Services Page
    "services.hero.cta": "Get a Free Consultation",
    "services.coreTitle": "Our Core Services",
    "services.coreSubtitle": "Explore our comprehensive range of services designed to meet your specific needs",
    "services.tabs.webDev": "Web Development",
    "services.tabs.mobileDev": "Mobile Development",
    "services.tabs.cloudSolutions": "Cloud Solutions",
    "services.tabs.itConsultancy": "IT Consultancy",
    "services.webDev.features.0": "Custom web application development",
    "services.webDev.features.1": "Progressive Web Apps (PWAs)",
    "services.webDev.features.2": "E-commerce solutions",
    "services.webDev.features.3": "Content Management Systems",
    "services.webDev.features.4": "API development and integration",
    "services.webDev.features.5": "Web portal development",
    "services.mobileDev.features.0": "Native iOS app development",
    "services.mobileDev.features.1": "Native Android app development",
    "services.mobileDev.features.2": "Cross-platform app development",
    "services.mobileDev.features.3": "Mobile app UI/UX design",
    "services.mobileDev.features.4": "App maintenance and support",
    "services.mobileDev.features.5": "App store optimization",
    "services.cloudSolutions.features.0": "Cloud migration services",
    "services.cloudSolutions.features.1": "Cloud-native application development",
    "services.cloudSolutions.features.2": "Serverless architecture",
    "services.cloudSolutions.features.3": "DevOps and CI/CD implementation",
    "services.cloudSolutions.features.4": "Cloud infrastructure management",
    "services.cloudSolutions.features.5": "Microservices architecture",
    "services.consultancy.features.0": "Technology strategy consulting",
    "services.consultancy.features.1": "Digital transformation",
    "services.consultancy.features.2": "Software architecture design",
    "services.consultancy.features.3": "Technical due diligence",
    "services.consultancy.features.4": "Team augmentation",
    "services.consultancy.features.5": "Technology training and workshops",
    "services.learnMore": "Learn More",
    "services.additionalTitle": "Additional Services",
    "services.additionalSubtitle": "Beyond our core offerings, we provide specialized services to address specific needs",
    "services.additional.db.title": "Database Solutions",
    "services.additional.db.desc": "Robust database design, optimization, and management services",
    "services.additional.cybersecurity.title": "Cybersecurity",
    "services.additional.cybersecurity.desc": "Comprehensive security solutions to protect your digital assets",
    "services.additional.ai.title": "AI & Machine Learning",
    "services.additional.ai.desc": "Intelligent solutions powered by advanced AI and ML technologies",
    "services.additional.devops.title": "DevOps Services",
    "services.additional.devops.desc": "Streamline your development and operations with our DevOps expertise",
    "services.processTitle": "Our Development Process",
    "services.processSubtitle": "A structured approach to deliver high-quality software solutions",
    "services.process.step1.title": "Discovery",
    "services.process.step1.desc": "We start by understanding your business goals, target audience, and project requirements through in-depth consultations.",
    "services.process.step2.title": "Planning",
    "services.process.step2.desc": "Our team creates a detailed project plan, including timelines, milestones, and resource allocation.",
    "services.process.step3.title": "Design",
    "services.process.step3.desc": "We design intuitive user interfaces and experiences that align with your brand and meet user needs.",
    "services.process.step4.title": "Development",
    "services.process.step4.desc": "Our developers build your solution using the latest technologies and best practices.",
    "services.process.step5.title": "Testing",
    "services.process.step5.desc": "Rigorous testing ensures your software is bug-free, secure, and performs optimally.",
    "services.process.step6.title": "Deployment",
    "services.process.step6.desc": "We deploy your solution to production environments and ensure smooth operation.",
    "services.process.step7.title": "Support",
    "services.process.step7.desc": "Ongoing maintenance and support keep your software running smoothly and up-to-date.",
    "services.caseStudiesTitle": "Case Studies",
    "services.caseStudiesSubtitle": "Explore how we've helped businesses achieve their goals",
    "services.caseStudies.ecommerce.title": "E-commerce Platform Redesign",
    "services.caseStudies.ecommerce.category": "Web Development",
    "services.caseStudies.ecommerce.desc": "Redesigned and rebuilt an e-commerce platform, resulting in a 40% increase in conversion rates and improved user experience.",
    "services.caseStudies.mobileBanking.title": "Mobile Banking App",
    "services.caseStudies.mobileBanking.category": "Mobile Development",
    "services.caseStudies.mobileBanking.desc": "Developed a secure and user-friendly mobile banking application with advanced features and biometric authentication.",
    "services.caseStudies.cloudMigration.title": "Cloud Migration for Enterprise",
    "services.caseStudies.cloudMigration.category": "Cloud Solutions",
    "services.caseStudies.cloudMigration.desc": "Migrated a large enterprise from legacy systems to a modern cloud infrastructure, reducing costs by 30% and improving scalability.",
    "services.caseStudies.readMore": "Read Case Study",
    "services.caseStudies.viewAll": "View All Case Studies",
    "services.pricingTitle": "Pricing Plans",
    "services.pricingSubtitle": "Flexible pricing options to suit businesses of all sizes",
    "services.pricing.basic.name": "Basic",
    "services.pricing.basic.price": "$5,000+",
    "services.pricing.basic.desc": "Perfect for small projects and startups",
    "services.pricing.basic.features.0": "Custom web development",
    "services.pricing.basic.features.1": "Responsive design",
    "services.pricing.basic.features.2": "Basic SEO optimization",
    "services.pricing.basic.features.3": "Content management system",
    "services.pricing.basic.features.4": "3 months of support",
    "services.pricing.professional.name": "Professional",
    "services.pricing.professional.price": "$15,000+",
    "services.pricing.professional.desc": "Ideal for growing businesses",
    "services.pricing.professional.features.0": "Advanced web application",
    "services.pricing.professional.features.1": "Mobile-friendly design",
    "services.pricing.professional.features.2": "API integrations",
    "services.pricing.professional.features.3": "E-commerce functionality",
    "services.pricing.professional.features.4": "Performance optimization",
    "services.pricing.professional.features.5": "6 months of support",
    "services.pricing.enterprise.name": "Enterprise",
    "services.pricing.enterprise.price": "Custom",
    "services.pricing.enterprise.desc": "For large-scale enterprise solutions",
    "services.pricing.enterprise.features.0": "Full-scale digital ecosystem",
    "services.pricing.enterprise.features.1": "Custom software development",
    "services.pricing.enterprise.features.2": "Advanced security features",
    "services.pricing.enterprise.features.3": "Third-party integrations",
    "services.pricing.enterprise.features.4": "Scalable architecture",
    "services.pricing.enterprise.features.5": "Dedicated support team",
    "services.pricing.enterprise.features.6": "12 months of support",
    "services.pricing.getStarted": "Get Started",
    "services.pricing.contactUs": "Contact Us",
    "services.pricing.customQuoteText": "Need a custom solution? Contact us for a personalized quote.",
    "services.pricing.contactUsButton": "Contact Us",
    "services.ctaTitle": "Ready to Start Your Project?",
    "services.ctaSubtitle": "Let's discuss your requirements and create a tailored solution for your business.",
    "services.cta.scheduleConsultation": "Schedule a Consultation",
    "services.cta.viewPortfolio": "View Our Portfolio",

    // About Page
    "about.story.p1": "Founded in 2015, Medusa began with a simple mission: to create innovative software solutions that help businesses thrive in the digital age.",
    "about.story.p2": "Our founder, Alex Johnson, recognized a gap in the market for a development company that truly understood both the technical and business aspects of software projects. With a background in both software engineering and business management, Alex assembled a team of like-minded professionals who shared his vision.",
    "about.story.p3": "Over the years, we've grown from a small team of passionate developers to a full-service software development company with expertise across multiple domains. Throughout our journey, we've maintained our commitment to quality, innovation, and client satisfaction.",
    "about.story.p4": "Today, Medusa serves clients across various industries, from startups to enterprise organizations, helping them transform their ideas into digital reality.",
    "about.mission.desc": "Our mission is to empower businesses through innovative software solutions that drive growth, enhance efficiency, and create exceptional user experiences.",
    "about.mission.item1": "Deliver high-quality software that exceeds expectations",
    "about.mission.item2": "Build long-term partnerships with our clients",
    "about.mission.item3": "Stay at the forefront of technological innovation",
    "about.mission.item4": "Create solutions that solve real business challenges",
    "about.vision.desc": "We envision a world where businesses of all sizes can harness the power of technology to achieve their full potential and create meaningful impact.",
    "about.vision.item1": "Become a global leader in software development",
    "about.vision.item2": "Set new standards for quality and innovation",
    "about.vision.item3": "Build a diverse and inclusive team of experts",
    "about.vision.item4": "Make advanced technology accessible to all businesses",
    "about.valuesTitle": "Our Values",
    "about.valuesSubtitle": "The core principles that guide everything we do",
    "about.values.innovation.title": "Innovation",
    "about.values.innovation.desc": "We constantly explore new technologies and approaches to deliver cutting-edge solutions.",
    "about.values.collaboration.title": "Collaboration",
    "about.values.collaboration.desc": "We believe in the power of teamwork and close collaboration with our clients.",
    "about.values.excellence.title": "Excellence",
    "about.values.excellence.desc": "We strive for excellence in everything we do, from code quality to client communication.",
    "about.values.clientFocus.title": "Client Focus",
    "about.values.clientFocus.desc": "Our clients' success is our success. We're committed to delivering solutions that drive business growth.",
    "about.journeyTitle": "Our Journey",
    "about.journeySubtitle": "Key milestones in our company's history",
    "about.journey.event1.year": "2015",
    "about.journey.event1.title": "Company Founded",
    "about.journey.event1.desc": "Medusa was founded with a vision to create innovative software solutions for businesses of all sizes.",
    "about.journey.event2.year": "2017",
    "about.journey.event2.title": "First Major Client",
    "about.journey.event2.desc": "Secured our first enterprise client and successfully delivered a complex web application.",
    "about.journey.event3.year": "2018",
    "about.journey.event3.title": "Team Expansion",
    "about.journey.event3.desc": "Grew our team to 15 talented developers, designers, and project managers.",
    "about.journey.event4.year": "2019",
    "about.journey.event4.title": "Mobile Development",
    "about.journey.event4.desc": "Expanded our services to include mobile application development for iOS and Android.",
    "about.journey.event5.year": "2020",
    "about.journey.event5.title": "Cloud Solutions",
    "about.journey.event5.desc": "Launched our cloud solutions division to help businesses migrate to and optimize cloud infrastructure.",
    "about.journey.event6.year": "2022",
    "about.journey.event6.title": "International Expansion",
    "about.journey.event6.desc": "Opened our first international office and began serving clients globally.",
    "about.journey.event7.year": "2023",
    "about.journey.event7.title": "AI & ML Services",
    "about.journey.event7.desc": "Introduced artificial intelligence and machine learning services to our portfolio.",
    "about.journey.event8.year": "Today",
    "about.journey.event8.title": "Continued Growth",
    "about.journey.event8.desc": "Continuing to grow and innovate while maintaining our commitment to excellence and client satisfaction.",
    "about.team.subtitle": "Meet the talented individuals behind our success",
    "about.team.member1.name": "Alex Johnson",
    "about.team.member1.position": "Founder & CEO",
    "about.team.member1.bio": "With over 15 years of experience in software development, Alex founded Medusa with a vision to create innovative digital solutions.",
    "about.team.member2.name": "Sarah Williams",
    "about.team.member2.position": "CTO",
    "about.team.member2.bio": "Sarah leads our technical team with her expertise in cloud architecture and emerging technologies.",
    "about.team.member3.name": "Michael Chen",
    "about.team.member3.position": "Lead Developer",
    "about.team.member3.bio": "Michael specializes in full-stack development and has led numerous successful projects for our enterprise clients.",
    "about.team.member4.name": "Emily Rodriguez",
    "about.team.member4.position": "UX/UI Designer",
    "about.team.member4.bio": "Emily creates intuitive and engaging user experiences that combine aesthetics with functionality.",
    "about.team.member5.name": "David Kim",
    "about.team.member5.position": "Mobile Development Lead",
    "about.team.member5.bio": "David has extensive experience in native and cross-platform mobile application development.",
    "about.team.member6.name": "Sophia Patel",
    "about.team.member6.position": "Project Manager",
    "about.team.member6.bio": "Sophia ensures our projects are delivered on time and within budget while maintaining the highest quality standards.",
    "about.joinTitle": "Join Our Team",
    "about.joinSubtitle": "We're always looking for talented individuals to join our growing team. Check out our current openings or send us your resume.",
    "about.join.viewOpenings": "View Open Positions",
    "about.join.sendResume": "Send Your Resume",
    "about.ctaTitle": "Ready to Work With Us?",
    "about.ctaSubtitle": "Let's discuss how we can help bring your ideas to life.",
    "about.cta.getInTouch": "Get in Touch",

    // Contact Page
    "contact.sendMessage": "Send Us a Message",
    "contact.contactInfo": "Contact Information",
    "contact.contactDesc": "Have questions or want to discuss your project? Reach out to us through any of these channels.",
    "contact.businessHours": "Business Hours",
    "contact.faqTitle": "Frequently Asked Questions",
    "contact.faqSubtitle": "Find answers to common questions about our services and process",
    "contact.ctaTitle": "Ready to Transform Your Ideas Into Reality?",
    "contact.ctaSubtitle": "Contact us today to discuss your project and get a free consultation.",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "How can we help you?",
    "contact.messagePlaceholder": "Tell us about your project...",
    "contact.privacyPolicy": "I agree to the Privacy Policy",
    "contact.sending": "Sending...",
    "contact.scheduleCall": "Schedule a Call",
    "contact.toast.success.title": "Message sent!",
    "contact.toast.success.description": "We'll get back to you as soon as possible.",
    "contact.address.detail": "123 Tech Street, Tbilisi, Georgia",
    "contact.phone.detail": "+995 123 456 789",
    "contact.email.detail": "info@medusa.dev",
    "contact.hours.mondayFriday": "Monday - Friday:",
    "contact.hours.mondayFridayTime": "9:00 AM - 6:00 PM",
    "contact.hours.saturday": "Saturday:",
    "contact.hours.saturdayTime": "10:00 AM - 4:00 PM",
    "contact.hours.sunday": "Sunday:",
    "contact.hours.sundayTime": "Closed",
    "contact.mapPlaceholder": "Interactive Map Would Be Here",
    "contact.faq.item1.question": "What is your typical process for new projects?",
    "contact.faq.item1.answer": "Our process typically includes discovery, planning, design, development, testing, deployment, and ongoing support phases. We start with understanding your requirements and business goals before creating a detailed project plan.",
    "contact.faq.item2.question": "How long does it take to complete a typical project?",
    "contact.faq.item2.answer": "Project timelines vary depending on complexity and scope. A simple website might take 4-6 weeks, while a complex web application could take 3-6 months. We provide detailed timelines during the planning phase.",
    "contact.faq.item3.question": "Do you provide ongoing support after the project is completed?",
    "contact.faq.item3.answer": "Yes, we offer various support and maintenance packages to ensure your software continues to run smoothly after launch. This includes bug fixes, security updates, and feature enhancements.",
    "contact.faq.item4.question": "What technologies do you specialize in?",
    "contact.faq.item4.answer": "We specialize in a wide range of technologies including React, Next.js, Node.js, Python, AWS, Docker, and more. Our team stays up-to-date with the latest advancements to provide cutting-edge solutions.",
    "contact.faq.item5.question": "How do you handle project communication?",
    "contact.faq.item5.answer": "We maintain transparent communication through regular meetings, progress reports, and dedicated project management tools. You'll have a dedicated project manager as your main point of contact.",
    "contact.faq.item6.question": "What is your pricing model?",
    "contact.faq.item6.answer": "We offer flexible pricing models including fixed-price projects, time and materials, and retainer arrangements. The best model depends on your project's nature and requirements.",
  },
  ka: {
    // Navigation
    "nav.home": "მთავარი",
    "nav.services": "სერვისები",
    "nav.about": "ჩვენ შესახებ",
    "nav.contact": "კონტაქტი",
    "nav.getStarted": "დაიწყე",
  
    // Hero Section (Main Page)
    "hero.title": "იდეების ციფრულ რეალობად გარდაქმნა",
    "hero.subtitle": "ჩვენ ვქმნით ინოვაციურ პროგრამულ გადაწყვეტილებებს, რომლებიც ხელს უწყობს ბიზნესის ზრდას და აუმჯობესებს მომხმარებლის გამოცდილებას",
    "hero.cta": "გაეცანით ჩვენს სერვისებს",
    "hero.secondary": "დაგვიკავშირდით",
  
    // Services Section (Main Page & Services Page)
    "services.title": "ჩვენი სერვისები",
    "services.subtitle": "ყოვლისმომცველი პროგრამული უზრუნველყოფის განვითარების გადაწყვეტილებები, მორგებული თქვენს საჭიროებებზე",
    "services.webDev": "ვებ განვითარება",
    "services.webDesc": "მორგებული ვებსაიტები და ვებ აპლიკაციები თანამედროვე ტექნოლოგიებით",
    "services.mobileDev": "მობილური განვითარება",
    "services.mobileDesc": "ნატიური და კროს-პლატფორმული მობილური აპლიკაციები iOS და Android-ისთვის",
    "services.cloudSolutions": "ღრუბლოვანი გადაწყვეტილებები",
    "services.cloudDesc": "მასშტაბური ღრუბლოვანი ინფრასტრუქტურა და განთავსების სერვისები",
    "services.consultancy": "IT კონსულტაცია",
    "services.consultancyDesc": "ექსპერტული რჩევები ტექნოლოგიური სტრატეგიისა და განხორციელების შესახებ",
  
    // About Section (Main Page & About Page)
    "about.title": "მედუზას შესახებ",
    "about.subtitle": "გუნდი, რომელიც ქმნის გამორჩეულ პროგრამულ უზრუნველყოფას",
    "about.story": "ჩვენი ისტორია",
    "about.mission": "ჩვენი მისია",
    "about.vision": "ჩვენი ხედვა",
    "about.team": "ჩვენი გუნდი",
  
    // Technologies Section (Main Page)
    "tech.title": "ტექნოლოგიები, რომლებსაც ვიყენებთ",
    "tech.subtitle": "ჩვენ ვიყენებთ უახლეს ტექნოლოგიებს მაღალი ხარისხის გადაწყვეტილებების მისაწოდებლად",
  
    // Testimonials Section (REMOVED FROM MAIN PAGE)
    "testimonials.title": "რას ამბობენ ჩვენი კლიენტები",
    "testimonials.subtitle": "მოისმინეთ იმ ბიზნესებისგან, რომელთა ტრანსფორმაციაშიც დავეხმარეთ",
  
    // Contact Section (Main Page & Contact Page)
    "contact.title": "დაგვიკავშირდით",
    "contact.subtitle": "გვსურს თქვენგან მოვისმინოთ",
    "contact.name": "სახელი",
    "contact.email": "ელ-ფოსტა",
    "contact.message": "შეტყობინება",
    "contact.submit": "შეტყობინების გაგზავნა",
    "contact.address": "მისამართი",
    "contact.phone": "ტელეფონი",
  
    // Footer
    "footer.rights": "ყველა უფლება დაცულია",
    "footer.privacy": "კონფიდენციალურობის პოლიტიკა",
    "footer.terms": "მომსახურების პირობები",
    "footer.companyInfo": "იდეების ციფრულ რეალობად გარდაქმნა ინოვაციური პროგრამული გადაწყვეტილებებით.",
  
    // Home Page Specific
    "home.cta.title": "მზად ხართ თქვენი იდეები რეალობად აქციოთ?",
    "home.cta.subtitle": "მოდით, ერთად შევქმნათ რაღაც საოცარი. დაგვიკავშირდით დღეს თქვენი პროექტის განსახილველად.",
    "home.cta.getStarted": "დაიწყეთ",
    "home.cta.learnMore": "შეიტყვეთ მეტი",
    "home.features.title": "რატომ უნდა აირჩიოთ მედუზა თქვენი პროგრამული უზრუნველყოფის განვითარებისთვის?",
    "home.features.subtitle": "ჩვენ ვაერთიანებთ ტექნიკურ ექსპერტიზას შემოქმედებით პრობლემების გადაჭრასთან, რათა შევქმნათ გამორჩეული პროგრამული გადაწყვეტილებები.",
    "home.features.item1": "დეველოპერების, დიზაინერებისა და სტრატეგების ექსპერტთა გუნდი",
    "home.features.item2": "უახლესი ტექნოლოგიები და საუკეთესო პრაქტიკები",
    "home.features.item3": "Agile განვითარების მეთოდოლოგია უფრო სწრაფი მიწოდებისთვის",
    "home.features.item4": "მასშტაბირებადი გადაწყვეტილებები, რომლებიც იზრდება თქვენს ბიზნესთან ერთად",
    "home.features.item5": "გამოყოფილი მხარდაჭერისა და ტექნიკური მომსახურების სერვისები",
    "home.features.exploreServices": "გაეცანით ჩვენს სერვისებს",
  
    // Services Page
    "services.hero.cta": "მიიღეთ უფასო კონსულტაცია",
    "services.coreTitle": "ჩვენი ძირითადი სერვისები",
    "services.coreSubtitle": "გაეცანით ჩვენი სერვისების სრულ სპექტრს, რომელიც შექმნილია თქვენი კონკრეტული საჭიროებების დასაკმაყოფილებლად",
    "services.tabs.webDev": "ვებ განვითარება",
    "services.tabs.mobileDev": "მობილური განვითარება",
    "services.tabs.cloudSolutions": "ღრუბლოვანი გადაწყვეტილებები",
    "services.tabs.itConsultancy": "IT კონსულტაცია",
    "services.webDev.features.0": "მორგებული ვებ აპლიკაციების განვითარება",
    "services.webDev.features.1": "პროგრესული ვებ აპლიკაციები (PWAs)",
    "services.webDev.features.2": "ელექტრონული კომერციის გადაწყვეტილებები",
    "services.webDev.features.3": "შინაარსის მართვის სისტემები (CMS)",
    "services.webDev.features.4": "API-ს განვითარება და ინტეგრაცია",
    "services.webDev.features.5": "ვებ პორტალების განვითარება",
    "services.mobileDev.features.0": "ნატიური iOS აპლიკაციების განვითარება",
    "services.mobileDev.features.1": "ნატიური Android აპლიკაციების განვითარება",
    "services.mobileDev.features.2": "კროს-პლატფორმული აპლიკაციების განვითარება",
    "services.mobileDev.features.3": "მობილური აპლიკაციის UI/UX დიზაინი",
    "services.mobileDev.features.4": "აპლიკაციის ტექნიკური მომსახურება და მხარდაჭერა",
    "services.mobileDev.features.5": "აპლიკაციების მაღაზიის ოპტიმიზაცია (ASO)",
    "services.cloudSolutions.features.0": "ღრუბლოვან გარემოში მიგრაციის სერვისები",
    "services.cloudSolutions.features.1": "ღრუბელზე-მშობლიური აპლიკაციების განვითარება",
    "services.cloudSolutions.features.2": "უსერვერო არქიტექტურა",
    "services.cloudSolutions.features.3": "DevOps და CI/CD იმპლემენტაცია",
    "services.cloudSolutions.features.4": "ღრუბლოვანი ინფრასტრუქტურის მართვა",
    "services.cloudSolutions.features.5": "მიკროსერვისების არქიტექტურა",
    "services.consultancy.features.0": "ტექნოლოგიური სტრატეგიის კონსულტაცია",
    "services.consultancy.features.1": "ციფრული ტრანსფორმაცია",
    "services.consultancy.features.2": "პროგრამული უზრუნველყოფის არქიტექტურის დიზაინი",
    "services.consultancy.features.3": "ტექნიკური Due Diligence",
    "services.consultancy.features.4": "გუნდის გაძლიერება (Team Augmentation)",
    "services.consultancy.features.5": "ტექნოლოგიური ტრენინგები და ვორქშოფები",
    "services.learnMore": "შეიტყვეთ მეტი",
    "services.additionalTitle": "დამატებითი სერვისები",
    "services.additionalSubtitle": "ჩვენი ძირითადი შეთავაზებების გარდა, ჩვენ გთავაზობთ სპეციალიზებულ სერვისებს კონკრეტული საჭიროებების დასაკმაყოფილებლად",
    "services.additional.db.title": "მონაცემთა ბაზის გადაწყვეტილებები",
    "services.additional.db.desc": "მყარი მონაცემთა ბაზის დიზაინი, ოპტიმიზაცია და მართვის სერვისები",
    "services.additional.cybersecurity.title": "კიბერუსაფრთხოება",
    "services.additional.cybersecurity.desc": "ყოვლისმომცველი უსაფრთხოების გადაწყვეტილებები თქვენი ციფრული აქტივების დასაცავად",
    "services.additional.ai.title": "ხელოვნური ინტელექტი და მანქანური სწავლება",
    "services.additional.ai.desc": "ინტელექტუალური გადაწყვეტილებები, მოწინავე AI და ML ტექნოლოგიებზე დაფუძნებული",
    "services.additional.devops.title": "DevOps სერვისები",
    "services.additional.devops.desc": "გაამარტივეთ თქვენი განვითარებისა და ოპერაციების პროცესები ჩვენი DevOps ექსპერტიზით",
    "services.processTitle": "ჩვენი განვითარების პროცესი",
    "services.processSubtitle": "სტრუქტურირებული მიდგომა მაღალი ხარისხის პროგრამული გადაწყვეტილებების მისაწოდებლად",
    "services.process.step1.title": "აღმოჩენა",
    "services.process.step1.desc": "ჩვენ ვიწყებთ თქვენი ბიზნეს მიზნების, სამიზნე აუდიტორიისა და პროექტის მოთხოვნების გააზრებით, სიღრმისეული კონსულტაციების საშუალებით.",
    "services.process.step2.title": "დაგეგმვა",
    "services.process.step2.desc": "ჩვენი გუნდი ქმნის პროექტის დეტალურ გეგმას, ვადების, ეტაპებისა და რესურსების განაწილების ჩათვლით.",
    "services.process.step3.title": "დიზაინი",
    "services.process.step3.desc": "ჩვენ ვქმნით ინტუიციურ მომხმარებლის ინტერფეისებსა და გამოცდილებებს, რომლებიც შეესაბამება თქვენს ბრენდს და აკმაყოფილებს მომხმარებლის საჭიროებებს.",
    "services.process.step4.title": "განვითარება",
    "services.process.step4.desc": "ჩვენი დეველოპერები ქმნიან თქვენს გადაწყვეტილებას უახლესი ტექნოლოგიებისა და საუკეთესო პრაქტიკების გამოყენებით.",
    "services.process.step5.title": "ტესტირება",
    "services.process.step5.desc": "საფუძვლიანი ტესტირება უზრუნველყოფს, რომ თქვენი პროგრამული უზრუნველყოფა იყოს უშეცდომო, უსაფრთხო და ოპტიმალურად მუშაობდეს.",
    "services.process.step6.title": "განთავსება",
    "services.process.step6.desc": "ჩვენ ვათავსებთ თქვენს გადაწყვეტილებას საპროდუქციო გარემოში და ვუზრუნველყოფთ მის გამართულ მუშაობას.",
    "services.process.step7.title": "მხარდაჭერა",
    "services.process.step7.desc": "მუდმივი ტექნიკური მომსახურება და მხარდაჭერა უზრუნველყოფს თქვენი პროგრამული უზრუნველყოფის გამართულ მუშაობასა და განახლებას.",
    "services.caseStudiesTitle": "ქეის სტადიები",
    "services.caseStudiesSubtitle": "გაეცანით, როგორ დავეხმარეთ ბიზნესებს მიზნების მიღწევაში",
    "services.caseStudies.ecommerce.title": "ელექტრონული კომერციის პლატფორმის რედიზაინი",
    "services.caseStudies.ecommerce.category": "ვებ განვითარება",
    "services.caseStudies.ecommerce.desc": "შევცვალეთ და თავიდან ავაშენეთ ელექტრონული კომერციის პლატფორმა, რამაც გამოიწვია კონვერტაციის მაჩვენებლის 40%-იანი ზრდა და მომხმარებლის გამოცდილების გაუმჯობესება.",
    "services.caseStudies.mobileBanking.title": "მობილური ბანკინგის აპლიკაცია",
    "services.caseStudies.mobileBanking.category": "მობილური განვითარება",
    "services.caseStudies.mobileBanking.desc": "შევქმენით უსაფრთხო და მომხმარებელზე მორგებული მობილური ბანკინგის აპლიკაცია მოწინავე ფუნქციებითა და ბიომეტრიული ავთენტიფიკაციით.",
    "services.caseStudies.cloudMigration.title": "ღრუბლოვანი მიგრაცია საწარმოსთვის",
    "services.caseStudies.cloudMigration.category": "ღრუბლოვანი გადაწყვეტილებები",
    "services.caseStudies.cloudMigration.desc": "დიდი საწარმო გადავიყვანეთ მოძველებული სისტემებიდან თანამედროვე ღრუბლოვან ინფრასტრუქტურაზე, რამაც ხარჯები 30%-ით შეამცირა და მასშტაბირებადობა გააუმჯობესა.",
    "services.caseStudies.readMore": "ქეისის სრულად წაკითხვა",
    "services.caseStudies.viewAll": "ყველა ქეისის ნახვა",
    "services.pricingTitle": "ფასების გეგმები",
    "services.pricingSubtitle": "მოქნილი ფასების ვარიანტები ყველა ზომის ბიზნესისთვის",
    "services.pricing.basic.name": "საბაზისო",
    "services.pricing.basic.price": "$5,000+",
    "services.pricing.basic.desc": "იდეალურია მცირე პროექტებისა და სტარტაპებისთვის",
    "services.pricing.basic.features.0": "მორგებული ვებ განვითარება",
    "services.pricing.basic.features.1": "რესპონსიული დიზაინი",
    "services.pricing.basic.features.2": "საბაზისო SEO ოპტიმიზაცია",
    "services.pricing.basic.features.3": "შინაარსის მართვის სისტემა",
    "services.pricing.basic.features.4": "3 თვიანი მხარდაჭერა",
    "services.pricing.professional.name": "პროფესიონალური",
    "services.pricing.professional.price": "$15,000+",
    "services.pricing.professional.desc": "იდეალურია მზარდი ბიზნესებისთვის",
    "services.pricing.professional.features.0": "მოწინავე ვებ აპლიკაცია",
    "services.pricing.professional.features.1": "მობილურზე მორგებული დიზაინი",
    "services.pricing.professional.features.2": "API ინტეგრაციები",
    "services.pricing.professional.features.3": "ელექტრონული კომერციის ფუნქციონალი",
    "services.pricing.professional.features.4": "წარმადობის ოპტიმიზაცია",
    "services.pricing.professional.features.5": "6 თვიანი მხარდაჭერა",
    "services.pricing.enterprise.name": "საწარმო",
    "services.pricing.enterprise.price": "ინდივიდუალური",
    "services.pricing.enterprise.desc": "დიდი მასშტაბის საწარმოო გადაწყვეტილებებისთვის",
    "services.pricing.enterprise.features.0": "სრულმასშტაბიანი ციფრული ეკოსისტემა",
    "services.pricing.enterprise.features.1": "მორგებული პროგრამული უზრუნველყოფის განვითარება",
    "services.pricing.enterprise.features.2": "მოწინავე უსაფრთხოების ფუნქციები",
    "services.pricing.enterprise.features.3": "მესამე მხარის ინტეგრაციები",
    "services.pricing.enterprise.features.4": "მასშტაბირებადი არქიტექტურა",
    "services.pricing.enterprise.features.5": "გამოყოფილი მხარდაჭერის გუნდი",
    "services.pricing.enterprise.features.6": "12 თვიანი მხარდაჭერა",
    "services.pricing.getStarted": "დაიწყეთ",
    "services.pricing.contactUs": "დაგვიკავშირდით",
    "services.pricing.customQuoteText": "გჭირდებათ ინდივიდუალური გადაწყვეტილება? დაგვიკავშირდით პერსონალიზებული შეთავაზებისთვის.",
    "services.pricing.contactUsButton": "დაგვიკავშირდით",
    "services.ctaTitle": "მზად ხართ პროექტის დასაწყებად?",
    "services.ctaSubtitle": "განვიხილოთ თქვენი მოთხოვნები და შევქმნათ თქვენს ბიზნესზე მორგებული გადაწყვეტილება.",
    "services.cta.scheduleConsultation": "დაგეგმეთ კონსულტაცია",
    "services.cta.viewPortfolio": "იხილეთ ჩვენი პორტფოლიო",
  
    // About Page
    "about.story.p1": "2015 წელს დაარსებული მედუზა მარტივი მისიით დაიწყო: შეექმნა ინოვაციური პროგრამული გადაწყვეტილებები, რომლებიც ბიზნესს ციფრულ ეპოქაში განვითარებაში დაეხმარებოდა.",
    "about.story.p2": "ჩვენმა დამფუძნებელმა, ალექს ჯონსონმა, ბაზარზე შენიშნა განვითარების კომპანიის საჭიროება, რომელიც ნამდვილად გაიგებდა პროგრამული პროექტების როგორც ტექნიკურ, ისე ბიზნეს ასპექტებს. პროგრამული ინჟინერიისა და ბიზნესის მართვის გამოცდილებით, ალექსმა შეკრიბა თანამოაზრე პროფესიონალთა გუნდი, რომლებიც მის ხედვას იზიარებდნენ.",
    "about.story.p3": "წლების განმავლობაში, ჩვენ გავიზარდეთ ენთუზიასტი დეველოპერების მცირე გუნდიდან სრული სერვისის პროგრამული უზრუნველყოფის განვითარების კომპანიამდე, მრავალ სფეროში ექსპერტიზით. ჩვენი მოგზაურობის განმავლობაში, ჩვენ შევინარჩუნეთ ერთგულება ხარისხის, ინოვაციისა და კლიენტთა კმაყოფილებისადმი.",
    "about.story.p4": "დღეს მედუზა ემსახურება კლიენტებს სხვადასხვა ინდუსტრიაში, სტარტაპებიდან მსხვილ ორგანიზაციებამდე, ეხმარება მათ იდეების ციფრულ რეალობად ქცევაში.",
    "about.mission.desc": "ჩვენი მისიაა ბიზნესების გაძლიერება ინოვაციური პროგრამული გადაწყვეტილებებით, რომლებიც ხელს უწყობს ზრდას, აუმჯობესებს ეფექტურობას და ქმნის გამორჩეულ მომხმარებლის გამოცდილებას.",
    "about.mission.item1": "მივაწოდოთ მაღალი ხარისხის პროგრამული უზრუნველყოფა, რომელიც მოლოდინს გადააჭარბებს",
    "about.mission.item2": "ავაშენოთ გრძელვადიანი პარტნიორობა ჩვენს კლიენტებთან",
    "about.mission.item3": "ვიყოთ ტექნოლოგიური ინოვაციების წინა ხაზზე",
    "about.mission.item4": "შევქმნათ გადაწყვეტილებები, რომლებიც რეალურ ბიზნეს გამოწვევებს წყვეტს",
    "about.vision.desc": "ჩვენ წარმოვიდგენთ სამყაროს, სადაც ყველა ზომის ბიზნესს შეუძლია გამოიყენოს ტექნოლოგიის ძალა სრული პოტენციალის მისაღწევად და მნიშვნელოვანი გავლენის მოსახდენად.",
    "about.vision.item1": "გავხდეთ გლობალური ლიდერი პროგრამული უზრუნველყოფის განვითარებაში",
    "about.vision.item2": "დავამკვიდროთ ხარისხისა და ინოვაციის ახალი სტანდარტები",
    "about.vision.item3": "შევქმნათ ექსპერტთა მრავალფეროვანი და ინკლუზიური გუნდი",
    "about.vision.item4": "გავხადოთ მოწინავე ტექნოლოგიები ხელმისაწვდომი ყველა ბიზნესისთვის",
    "about.valuesTitle": "ჩვენი ღირებულებები",
    "about.valuesSubtitle": "ძირითადი პრინციპები, რომლებიც განსაზღვრავს ყველაფერს, რასაც ვაკეთებთ",
    "about.values.innovation.title": "ინოვაცია",
    "about.values.innovation.desc": "ჩვენ მუდმივად ვიკვლევთ ახალ ტექნოლოგიებსა და მიდგომებს უახლესი გადაწყვეტილებების მისაწოდებლად.",
    "about.values.collaboration.title": "თანამშრომლობა",
    "about.values.collaboration.desc": "ჩვენ გვჯერა გუნდური მუშაობისა და ჩვენს კლიენტებთან მჭიდრო თანამშრომლობის ძალის.",
    "about.values.excellence.title": "სრულყოფილება",
    "about.values.excellence.desc": "ჩვენ ვისწრაფვით სრულყოფილებისკენ ყველაფერში, რასაც ვაკეთებთ, კოდის ხარისხიდან კლიენტთან კომუნიკაციამდე.",
    "about.values.clientFocus.title": "კლიენტზე ფოკუსირება",
    "about.values.clientFocus.desc": "ჩვენი კლიენტების წარმატება ჩვენი წარმატებაა. ჩვენ მზად ვართ მივაწოდოთ გადაწყვეტილებები, რომლებიც ბიზნესის ზრდას უწყობს ხელს.",
    "about.journeyTitle": "ჩვენი მოგზაურობა",
    "about.journeySubtitle": "მნიშვნელოვანი ეტაპები ჩვენი კომპანიის ისტორიაში",
    "about.journey.event1.year": "2015",
    "about.journey.event1.title": "კომპანია დაარსდა",
    "about.journey.event1.desc": "მედუზა დაარსდა ხედვით, შეექმნა ინოვაციური პროგრამული გადაწყვეტილებები ყველა ზომის ბიზნესისთვის.",
    "about.journey.event2.year": "2017",
    "about.journey.event2.title": "პირველი მსხვილი კლიენტი",
    "about.journey.event2.desc": "მოვიპოვეთ ჩვენი პირველი საწარმოო კლიენტი და წარმატებით მივაწოდეთ კომპლექსური ვებ აპლიკაცია.",
    "about.journey.event3.year": "2018",
    "about.journey.event3.title": "გუნდის გაფართოება",
    "about.journey.event3.desc": "გავზარდეთ ჩვენი გუნდი 15 ნიჭიერ დეველოპერამდე, დიზაინერამდე და პროექტის მენეჯერამდე.",
    "about.journey.event4.year": "2019",
    "about.journey.event4.title": "მობილური განვითარება",
    "about.journey.event4.desc": "გავაფართოვეთ ჩვენი სერვისები iOS და Android-ისთვის მობილური აპლიკაციების განვითარების ჩათვლით.",
    "about.journey.event5.year": "2020",
    "about.journey.event5.title": "ღრუბლოვანი გადაწყვეტილებები",
    "about.journey.event5.desc": "გავუშვით ჩვენი ღრუბლოვანი გადაწყვეტილებების განყოფილება, რათა დავეხმაროთ ბიზნესებს ღრუბლოვან ინფრასტრუქტურაზე მიგრაციასა და ოპტიმიზაციაში.",
    "about.journey.event6.year": "2022",
    "about.journey.event6.title": "საერთაშორისო გაფართოება",
    "about.journey.event6.desc": "გავხსენით ჩვენი პირველი საერთაშორისო ოფისი და დავიწყეთ კლიენტების მომსახურება გლობალურად.",
    "about.journey.event7.year": "2023",
    "about.journey.event7.title": "AI და ML სერვისები",
    "about.journey.event7.desc": "ჩვენს პორტფოლიოს დავამატეთ ხელოვნური ინტელექტისა და მანქანური სწავლების სერვისები.",
    "about.journey.event8.year": "დღეს",
    "about.journey.event8.title": "განგრძობითი ზრდა",
    "about.journey.event8.desc": "ვაგრძელებთ ზრდასა და ინოვაციას, სრულყოფილებისა და კლიენტთა კმაყოფილებისადმი ჩვენი ერთგულების შენარჩუნებით.",
    "about.team.subtitle": "გაიცანით ჩვენი წარმატების უკან მდგომი ნიჭიერი ადამიანები",
    "about.team.member1.name": "ალექს ჯონსონი",
    "about.team.member1.position": "დამფუძნებელი და აღმასრულებელი დირექტორი",
    "about.team.member1.bio": "პროგრამული უზრუნველყოფის განვითარებაში 15 წელზე მეტი გამოცდილებით, ალექსმა დააარსა მედუზა ინოვაციური ციფრული გადაწყვეტილებების შექმნის ხედვით.",
    "about.team.member2.name": "სარა უილიამსი",
    "about.team.member2.position": "ტექნიკური დირექტორი (CTO)",
    "about.team.member2.bio": "სარა ხელმძღვანელობს ჩვენს ტექნიკურ გუნდს ღრუბლოვანი არქიტექტურისა და ახალი ტექნოლოგიების სფეროში თავისი ექსპერტიზით.",
    "about.team.member3.name": "მაიკლ ჩენი",
    "about.team.member3.position": "წამყვანი დეველოპერი",
    "about.team.member3.bio": "მაიკლი სპეციალიზებულია full-stack განვითარებაში და უხელმძღვანელა მრავალ წარმატებულ პროექტს ჩვენი საწარმოო კლიენტებისთვის.",
    "about.team.member4.name": "ემილი როდრიგესი",
    "about.team.member4.position": "UX/UI დიზაინერი",
    "about.team.member4.bio": "ემილი ქმნის ინტუიციურ და მიმზიდველ მომხმარებლის გამოცდილებებს, რომლებიც აერთიანებს ესთეტიკასა და ფუნქციონალურობას.",
    "about.team.member5.name": "დევიდ კიმი",
    "about.team.member5.position": "მობილური განვითარების ხელმძღვანელი",
    "about.team.member5.bio": "დევიდს აქვს დიდი გამოცდილება ნატიური და კროს-პლატფორმული მობილური აპლიკაციების განვითარებაში.",
    "about.team.member6.name": "სოფია პატელი",
    "about.team.member6.position": "პროექტის მენეჯერი",
    "about.team.member6.bio": "სოფია უზრუნველყოფს ჩვენი პროექტების დროულად და ბიუჯეტის ფარგლებში მიწოდებას, უმაღლესი ხარისხის სტანდარტების დაცვით.",
    "about.joinTitle": "შემოგვიერთდით",
    "about.joinSubtitle": "ჩვენ ყოველთვის ვეძებთ ნიჭიერ ადამიანებს ჩვენს მზარდ გუნდში. გაეცანით ჩვენს მიმდინარე ვაკანსიებს ან გამოგვიგზავნეთ თქვენი რეზიუმე.",
    "about.join.viewOpenings": "იხილეთ ვაკანსიები",
    "about.join.sendResume": "გამოაგზავნეთ თქვენი რეზიუმე",
    "about.ctaTitle": "მზად ხართ ჩვენთან სამუშაოდ?",
    "about.ctaSubtitle": "განვიხილოთ, როგორ შეგვიძლია დაგეხმაროთ თქვენი იდეების რეალიზებაში.",
    "about.cta.getInTouch": "დაგვიკავშირდით",
  
    // Contact Page
    "contact.sendMessage": "გამოგვიგზავნეთ შეტყობინება",
    "contact.contactInfo": "საკონტაქტო ინფორმაცია",
    "contact.contactDesc": "გაქვთ კითხვები ან გსურთ განიხილოთ თქვენი პროექტი? დაგვიკავშირდით ნებისმიერი ამ არხის საშუალებით.",
    "contact.businessHours": "სამუშაო საათები",
    "contact.faqTitle": "ხშირად დასმული კითხვები",
    "contact.faqSubtitle": "იპოვეთ პასუხები ჩვენი სერვისებისა და პროცესის შესახებ ხშირად დასმულ კითხვებზე",
    "contact.ctaTitle": "მზად ხართ თქვენი იდეების რეალობად გარდასაქმნელად?",
    "contact.ctaSubtitle": "დაგვიკავშირდით დღესვე თქვენი პროექტის განსახილველად და უფასო კონსულტაციის მისაღებად.",
    "contact.subject": "თემა",
    "contact.subjectPlaceholder": "როგორ შეგვიძლია დაგეხმაროთ?",
    "contact.messagePlaceholder": "მოგვიყევით თქვენი პროექტის შესახებ...",
    "contact.privacyPolicy": "ვეთანხმები კონფიდენციალურობის პოლიტიკას",
    "contact.sending": "იგზავნება...",
    "contact.scheduleCall": "დაგეგმეთ ზარი",
    "contact.toast.success.title": "შეტყობინება გაიგზავნა!",
    "contact.toast.success.description": "ჩვენ რაც შეიძლება მალე დაგიკავშირდებით.",
    "contact.address.detail": "ტექ. ქუჩა 123, თბილისი, საქართველო",
    "contact.phone.detail": "+995 123 456 789",
    "contact.email.detail": "info@medusa.dev",
    "contact.hours.mondayFriday": "ორშაბათი - პარასკევი:",
    "contact.hours.mondayFridayTime": "9:00 - 18:00",
    "contact.hours.saturday": "შაბათი:",
    "contact.hours.saturdayTime": "10:00 - 16:00",
    "contact.hours.sunday": "კვირა:",
    "contact.hours.sundayTime": "დაკეტილია",
    "contact.mapPlaceholder": "ინტერაქტიული რუკა აქ განთავსდებოდა",
    "contact.faq.item1.question": "რა არის თქვენი ტიპური პროცესი ახალი პროექტებისთვის?",
    "contact.faq.item1.answer": "ჩვენი პროცესი, როგორც წესი, მოიცავს აღმოჩენის, დაგეგმვის, დიზაინის, განვითარების, ტესტირების, განთავსებისა და მუდმივი მხარდაჭერის ფაზებს. ვიწყებთ თქვენი მოთხოვნებისა და ბიზნეს მიზნების გაგებით, სანამ შევქმნით დეტალურ პროექტის გეგმას.",
    "contact.faq.item2.question": "რამდენი ხანი სჭირდება ტიპური პროექტის დასრულებას?",
    "contact.faq.item2.answer": "პროექტის ვადები განსხვავდება სირთულისა და მოცულობის მიხედვით. მარტივ ვებსაიტს შეიძლება 4-6 კვირა დასჭირდეს, ხოლო რთულ ვებ აპლიკაციას – 3-6 თვე. ჩვენ დეტალურ ვადებს დაგეგმვის ფაზაში წარმოგიდგენთ.",
    "contact.faq.item3.question": "აწვდით თუ არა მუდმივ მხარდაჭერას პროექტის დასრულების შემდეგ?",
    "contact.faq.item3.answer": "დიახ, ჩვენ გთავაზობთ სხვადასხვა მხარდაჭერისა და ტექნიკური მომსახურების პაკეტებს, რათა უზრუნველვყოთ თქვენი პროგრამული უზრუნველყოფის გამართული მუშაობა გაშვების შემდეგ. ეს მოიცავს ხარვეზების გამოსწორებას, უსაფრთხოების განახლებებსა და ფუნქციების გაუმჯობესებას.",
    "contact.faq.item4.question": "რომელ ტექნოლოგიებში სპეციალიზდებით?",
    "contact.faq.item4.answer": "ჩვენ ვსპეციალიზდებით ტექნოლოგიების ფართო სპექტრში, მათ შორის React, Next.js, Node.js, Python, AWS, Docker და სხვა. ჩვენი გუნდი მუდმივად ეცნობა უახლეს მიღწევებს, რათა შემოგთავაზოთ თანამედროვე გადაწყვეტილებები.",
    "contact.faq.item5.question": "როგორ უზრუნველყოფთ პროექტზე კომუნიკაციას?",
    "contact.faq.item5.answer": "ჩვენ ვუზრუნველყოფთ გამჭვირვალე კომუნიკაციას რეგულარული შეხვედრების, პროგრესის ანგარიშებისა და გამოყოფილი პროექტის მართვის ინსტრუმენტების საშუალებით. გეყოლებათ გამოყოფილი პროექტის მენეჯერი, როგორც თქვენი მთავარი საკონტაქტო პირი.",
    "contact.faq.item6.question": "რა არის თქვენი ფასების მოდელი?",
    "contact.faq.item6.answer": "ჩვენ გთავაზობთ მოქნილ ფასების მოდელებს, მათ შორის ფიქსირებული ფასის პროექტებს, დროისა და მასალების მიხედვით ანგარიშსწორებას და სააბონენტო ხელშეკრულებებს. საუკეთესო მოდელი დამოკიდებულია თქვენი პროექტის ბუნებასა და მოთხოვნებზე."
  }
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
})

export const useLanguage = () => useContext(LanguageContext)

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ka")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const langTranslations = translations[language] as any
    return langTranslations[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}